version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=api.powerit.loc
    volumes:
      - .:/var/www/html:delegated
    networks:
      - backend
      - proxy_proxy

  postgres:
    image: postgres:alpine
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=<%= db %>
      - POSTGRES_USER=postgres

networks:
  backend:
    driver: bridge
  proxy_proxy:
    external: true
